Module 1: Day 4 - Portfolio Project
Strangeal/Portfolio pull request #2
Opened 2022-08-18 10:43 UTC by Strangeal

Added 4 work cards and relevant styles

2022-08-18 19:15 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 

Hi @Strangeal 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif)

## Highlights
✅ No linter error
✅ README is professional

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- [x] I would suggest you use good commit messages since their very descriptive while tracking the changes in your project 😁 
- [ ] Kindly make your pull request more descriptive so as to let us know what you implemented in the current branch 😀 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-08-18 19:15 UTC, MaganaAsiati commented on header.html
> +                    <h1>Tonic</h1>
- [x] Kindly replace `<h2>` with `<h1>` tag and make sure there's only one `<h1>` tag on a web page for SEO reasons. you should only have one `<h1>` in your code 👍

2022-08-18 19:15 UTC, MaganaAsiati commented on header.html
> +                <h1>About Myself</h1>
- [x] Kindly replace `<h2>` with `<h1>` tag and make sure there's only one `<h1>` tag on a web page for SEO reasons. you should only have one `<h1>` in your code 👍

2022-08-18 19:15 UTC, MaganaAsiati commented on header.html
> +                    </ul>
- [x] Good job by trying to implement the languages buttons list of skills, but something went bad. you didn't implement them as on the Figma design. Kindly make it match the design.
### Your design:
![WhatsApp Image 2022-08-18 at 8 42 37 PM](https://user-images.githubusercontent.com/95297251/185472115-9c2b72ab-adc7-436e-8aa8-318d22130e32.jpeg)

### Figma design:
<img width="348" alt="Screen Shot 2022-08-18 at 20 54 16" src="https://user-images.githubusercontent.com/95297251/185472559-fb285f44-c89a-4557-a385-adef13bdcd9a.png">

2022-08-18 19:15 UTC, MaganaAsiati commented on header.html
> +                </ul>
- [x] Good job by trying to implement the languages icons list of skills, but something went bad. you didn't implement them as on the Figma design, kindly fix that 👍 

## Your design

![WhatsApp Image 2022-08-18 at 8 44 39 PM (1)](https://user-images.githubusercontent.com/95297251/185472195-0fc0f0d6-1837-42cf-9fa3-d4abc12954c9.jpeg)

## Figma design

<img width="348" alt="Screen Shot 2022-08-18 at 21 10 55" src="https://user-images.githubusercontent.com/95297251/185475649-522a13a8-8d2b-48a5-af21-a9a0f07d3d9d.png">

2022-08-19 00:08 UTC, Reem-lab requested changes
# Hi @Strangeal, 👋🏻👋🏻 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

 ## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the functionality ✅
📌 Good commit messages ✅
📌Professional README file. ✅

 ## Required Changes ♻️
_Check the comments under the review._
- [ REQUIRED ] Kindly make all the changes that the previous code reviewer asked because it is important to flow the sugesstion to make your code more cleasn dry and match the Figma design as much as possible 🚀💯💯✨✨

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 07:45 UTC, awais-amjed approved these changes
# STATUS: APPROVED 🥳

Hi @Strangeal , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations on successfully implementing the required changes! 🎉👏🥇✨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 07:46 UTC, merged