Module 1: Week 2(D4) - Portfolio Project
Strangeal/Portfolio pull request #4
Opened 2022-08-25 09:56 UTC by Strangeal

### Desktop View - Portfolio Project

Added media queries

2022-08-25 10:36 UTC, Nemwel-Boniface requested changes
## Hello @Strangeal           :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

You have done an amazing job with your portfolio desktop version so far :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] Kindly ensure that you stick as much as possible to the chosen Figma design in font sizes, font colors etc.

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 10:36 UTC, Nemwel-Boniface commented on header.html
> +                <h1>I’m Justice Glad to see you!</h1>
- [ ] Kindly note that you are required to stick as much as possible to the provided Figma design in fonts, colors, etc. The font size used is 6rem which makes it around 96px. Kindly change it to 48px as specified in the Figma design

2022-08-25 10:36 UTC, Nemwel-Boniface commented on header.html
> +                </p>
- [ ] Kindly note that you are required to stick as much as possible to the provided Figma design in fonts, colors, etc. The font size for this logo should be 18px as specified in the Figma design.

2022-08-25 10:36 UTC, Nemwel-Boniface commented on header.html
> +                <p>I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need code
- [ ] Kindly note that you are required to stick as much as possible to the provided Figma design in fonts, colors, etc. The font size for this p should be 20px as specified in the Figma design.

2022-08-25 10:36 UTC, Nemwel-Boniface commented on header.html
>                  <ul class="social-icons">
- [ ] Kindly note that you are required to stick as much as possible to the provided Figma design in fonts, colors, etc. Kindly reduce the size of these icons to match the provided Figma design.

2022-08-25 10:36 UTC, Nemwel-Boniface commented on header.html
> +                <p>A daily selection of privately personalized reads; no accounts or sign-ups required.</p>
- [ ] Kindly note that you are required to stick as much as possible to the provided Figma design in fonts, colors, etc. The font size for this p should be 16px as specified in the Figma design.

**Kindly implement this on all the ```<p>``` for the works section**

2022-08-25 11:22 UTC, cynthiainga approved these changes
Hi @Strangeal, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Good implementation of required changes ✔️ 
- [ ] Correct Github flow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 11:24 UTC, merged

2022-08-26 07:23 UTC, Nedramrez reviewed
Hi!
Nice job so far!
Please check the Figma design of your project.

2022-08-26 07:23 UTC, Nedramrez commented on header.html
> +            <div class="form-child">
Pleadse check the padding of `"form-child" <div>` and try to make it closer to the Figma design.

2022-08-26 07:23 UTC, Nedramrez commented on header.html
> +                <h1>I’m Justice Glad to see you!</h1>
Please check the` padding-top` property of the `"dev-child" <div>` so your headline section would be as it is at Figma design.